### ISSUE TITLE
jq: parse error

### ISSUE THREAD

**Issue by meaz** [justineuro/h5p-mcq-maker#1]
I got `jq: parse error: Expected another array element at line 308, column 2` when running `./mcq2h5p.sh test.txt`.

**Comment by justineuroFCC** [comment]
Would it be possible for you to share the contents of `test.txt` and `control.txt`?

**Comment by meaz** [comment]
I found the issue: the `N_QUESTIONS` number in `control.txt` must match the number of questions in `test.txt`. Obvious...

Perhaps I could suggest that `N_QUESTIONS` be removed and automatically use the number of questions set in `test.txt`.

**Comment by justineuroPTX** [comment]
Great to know that @meaz! 
Yes, as the current script is written, the total number of questions in the `questions file` (this is the `test.txt` file for you) that is given as input at the command line has to be indicated in the `N_QUESTIONS:` entry of the the `control.txt` file.
Indicating the total number of questions in the `control.txt` file beforehand provides for a way to ensure that the `questions file` (i.e., the `test.txt` file) indeed has all the intended questions and that all of these questions were read to create the H5P, so I think it is better to leave it that way.  Hoping this is okay with you.

**Comment by justineuro** [comment]
Let me close this issue now.

**Comment by justineuro** [comment]
I have written an alternative bash script, [**`mcq2h5p-eof.sh`**](https://raw.githubusercontent.com/justineuro/h5p-mcq-maker/master/mcq2h5p-eof.sh),  that is similar to the original script [**`mcq2h5p.sh`**](https://raw.githubusercontent.com/justineuro/h5p-mcq-maker/master/mcq2h5p.sh).  This alternative script does not require the initialization of the total number of questions `N_QUESTIONS` in the control file (`control-eof.txt`) for use with this bash script.

**Comment by meaz** [comment]
great thanks a lot!

**Comment by justineuro** [comment]
Okay!  Let me close this issue now.  Feel free to re-open this whenever a related issue arises in the future.
